-- Scripts de criação de tabelas e estruturas do Banco de Dados Oracle

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = RM562795;

-- Remover tabelas antigas se existirem (para facilitar testes e reinicialização)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_SATELITE_DADOS CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_ALERTA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_LEITURA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_ATUADOR CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_SENSOR CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_PROPRIEDADE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TB_USUARIO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Remover sequências se existirem
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PROPRIEDADE';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SENSOR';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ATUADOR';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ALERTA';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SATELITE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Sequências para autoincremento dos IDs (DEVEM ser criadas ANTES das tabelas)
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROPRIEDADE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SENSOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ATUADOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALERTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SATELITE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 1. TB_USUARIO
CREATE TABLE TB_USUARIO (
    id_usuario NUMBER(19) DEFAULT SEQ_USUARIO.NEXTVAL PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(255) NOT NULL,
    perfil VARCHAR2(20) NOT NULL CONSTRAINT chk_usuario_perfil CHECK (perfil IN ('USER', 'ESP32', 'ADMIN')),
    ativo NUMBER(1) DEFAULT 1 NOT NULL
);

-- 2. TB_PROPRIEDADE
CREATE TABLE TB_PROPRIEDADE (
    id_propriedade NUMBER(19) DEFAULT SEQ_PROPRIEDADE.NEXTVAL PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    localizacao VARCHAR2(255) NOT NULL,
    tamanho NUMBER(10, 2) NOT NULL, -- em hectares
    id_usuario NUMBER(19) NOT NULL,
    CONSTRAINT fk_propriedade_usuario FOREIGN KEY (id_usuario) REFERENCES TB_USUARIO(id_usuario) ON DELETE CASCADE
);

-- 3. TB_SENSOR
CREATE TABLE TB_SENSOR (
    id_sensor NUMBER(19) DEFAULT SEQ_SENSOR.NEXTVAL PRIMARY KEY,
    tipo_sensor VARCHAR2(50) NOT NULL CONSTRAINT chk_sensor_tipo CHECK (tipo_sensor IN ('UMIDADE', 'LUMINOSIDADE')),
    modelo VARCHAR2(100) NOT NULL,
    status VARCHAR2(20) NOT NULL CONSTRAINT chk_sensor_status CHECK (status IN ('ATIVO', 'INATIVO')),
    id_propriedade NUMBER(19) NOT NULL,
    CONSTRAINT fk_sensor_propriedade FOREIGN KEY (id_propriedade) REFERENCES TB_PROPRIEDADE(id_propriedade) ON DELETE CASCADE
);

-- 4. TB_ATUADOR
CREATE TABLE TB_ATUADOR (
    id_atuador NUMBER(19) DEFAULT SEQ_ATUADOR.NEXTVAL PRIMARY KEY,
    tipo_atuador VARCHAR2(50) NOT NULL CONSTRAINT chk_atuador_tipo CHECK (tipo_atuador IN ('BOMBA_AGUA', 'VALVULA_SOLENOIDE', 'ASPERSOR')),
    modelo VARCHAR2(100) NOT NULL,
    status VARCHAR2(20) NOT NULL CONSTRAINT chk_atuador_status CHECK (status IN ('ATIVO', 'INATIVO')),
    estado_atual VARCHAR2(20) NOT NULL CONSTRAINT chk_atuador_estado CHECK (estado_atual IN ('LIGADO', 'DESLIGADO')),
    id_propriedade NUMBER(19) NOT NULL,
    CONSTRAINT fk_atuador_propriedade FOREIGN KEY (id_propriedade) REFERENCES TB_PROPRIEDADE(id_propriedade) ON DELETE CASCADE
);

-- 5. TB_LEITURA (Histórico de leituras dos sensores enviadas pelo ESP32 - Chave Composta)
CREATE TABLE TB_LEITURA (
    id_sensor NUMBER(19) NOT NULL,
    data_leitura TIMESTAMP NOT NULL,
    valor NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_leitura PRIMARY KEY (id_sensor, data_leitura),
    CONSTRAINT fk_leitura_sensor FOREIGN KEY (id_sensor) REFERENCES TB_SENSOR(id_sensor) ON DELETE CASCADE
);

-- 6. TB_ALERTA (Registros de alarmes disparados por leituras críticas)
CREATE TABLE TB_ALERTA (
    id_alerta NUMBER(19) DEFAULT SEQ_ALERTA.NEXTVAL PRIMARY KEY,
    mensagem VARCHAR2(255) NOT NULL,
    data_alerta TIMESTAMP NOT NULL,
    id_propriedade NUMBER(19) NOT NULL,
    CONSTRAINT fk_alerta_propriedade FOREIGN KEY (id_propriedade) REFERENCES TB_PROPRIEDADE(id_propriedade) ON DELETE CASCADE
);

-- 7. TB_SATELITE_DADOS (Dados climáticos capturados via satélite para análise)
CREATE TABLE TB_SATELITE_DADOS (
    id_satelite NUMBER(19) DEFAULT SEQ_SATELITE.NEXTVAL PRIMARY KEY,
    umidade_prevista NUMBER(5, 2) NOT NULL,
    clima VARCHAR2(50) NOT NULL,
    regiao VARCHAR2(100) NOT NULL,
    data_coleta TIMESTAMP NOT NULL
);

-- Índices para chaves estrangeiras (Foreign Keys) para otimização de Joins e desempenho do banco
CREATE INDEX IDX_PROPRIEDADE_USUARIO ON TB_PROPRIEDADE(id_usuario);
CREATE INDEX IDX_SENSOR_PROPRIEDADE ON TB_SENSOR(id_propriedade);
CREATE INDEX IDX_ATUADOR_PROPRIEDADE ON TB_ATUADOR(id_propriedade);
CREATE INDEX IDX_ALERTA_PROPRIEDADE ON TB_ALERTA(id_propriedade);
